language: cpp
compiler: clang
dist: trusty
os: linux
include:
   # works on Trusty
   addons:
      apt:
         sources:
         - llvm-toolchain-trusty-12.0
         - george-edison55-precise-backports
         packages:
         - clang-12.0
         - cmake-data
         - cmake
   env:
      - MATRIX_EVAL="CC=clang-12.0 && CXX=clang++-12.0"
   global:
      - PRETTYNAME="DIY Air Sensor code"
branches:
   only:
      - main
notifications:
   email: true
before_install:
   - eval "${MATRIX_EVAL}"
   # - source $TRAVIS_BUILD_DIR/setup_travis_env.sh

install:
# # https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc
#    - arduino --install-library "AltSoftSerial","MemoryUsage","Stepper"
   # Install cpplint for style check
   - /usr/bin/python -m pip install --user cpplint
   - /usr/bin/python -m pip install --user cpp-coveralls

   # first we create a directory for the CMake binaries
   # Install CMAKE
   - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
   - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
   # we use wget to fetch the cmake binaries
   - travis_retry wget --no-check-certificate https://cmake.org/files/v3.19/cmake-3.19.0-Linux-x86_64.tar.gz
   # extract the binaries; the output here is quite lengthy,
   # so we swallow it to not clutter up the travis console
   - tar -xvf cmake-3.19.0-Linux-x86_64.tar.gz > /dev/null
   - mv cmake-3.19.0-Linux-x86_64 cmake-install
   # add both the top-level directory and the bin directory from the archive
   # to the system PATH. By adding it to the front of the path we hide the
   # preinstalled CMake with our own.
   - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
   # don't forget to switch back to the main build directory once you are done
   - cd ${TRAVIS_BUILD_DIR}

# this is where you run stuff
script:
   # do a linting pass
   - ./run_lint.bash
   # build and run tests
   - cd test && ./build.sh

# Generate and deploy documentation
after_success:
   - echo "todo - get automatic documentation generation working"
   - COVERALLS_REPO_TOKEN=CteyznTyrfm3aLBu5XefQ1fU9K5fqFoZ1 cpp-coveralls --skip-ssl-verify
#  - echo TRAVIS_BUILD_DIR is ${TRAVIS_BUILD_DIR}
#  - export DOXYFILE=${TRAVIS_BUILD_DIR}/Doxyfile
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
#  - source $TRAVIS_BUILD_DIR/doxy_gen_and_deploy.sh
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
