language: cpp
compiler: clang
dist: trusty
os: linux
include:
   # works on Trusty
   addons:
      apt:
         sources:
         - llvm-toolchain-trusty-5.0
         - george-edison55-precise-backports
         packages:
         - clang-5.0
         - cmake-data
         - cmake
   env:
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
   global:
      - PRETTYNAME="DIY Air Sensor code"
branches:
   only:
      - main
notifications:
   email: true
before_install:
   - eval "${MATRIX_EVAL}"
   # - source $TRAVIS_BUILD_DIR/setup_travis_env.sh

install:
# # https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc
#    - arduino --install-library "AltSoftSerial","MemoryUsage","Stepper"
# Install cpplint for style check
   - /usr/bin/python -m pip install --user cpplint

script:
#    - build_main_platforms
# do a linting pass
   - ./run_lint.bash
   - cd test && ./build.sh

# Generate and deploy documentation
after_success:
   - echo "todo: get automatic documentation generation working"
#  - echo TRAVIS_BUILD_DIR is ${TRAVIS_BUILD_DIR}
#  - export DOXYFILE=${TRAVIS_BUILD_DIR}/Doxyfile
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
#  - source $TRAVIS_BUILD_DIR/doxy_gen_and_deploy.sh
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
